### ISSUE TITLE
Error on Laravel 6.1.*

### ISSUE THREAD

**Issue by kamyasimon** [mtvbrianking/laravel-mtn-momo#23]
in the previous versions of laravel, the arrays were showin number on running 
php artisan mtn-momo:init,

but in Laravel 6.1.*, i get this error when selecting the currency and the product.

Use 'EUR' for sandbox environment

 ?[32mMOMO_CURRENCY?[39m [?[33mEUR?[39m]:
 >

?[1mProduct?[22m

 ?[32mMOMO_PRODUCT?[39m [?[33mcollection?[39m]:
  [?[33m0?[39m] collection
  [?[33m1?[39m] disbursement
  [?[33m2?[39m] remittance
 >
![issue](https://user-images.githubusercontent.com/30229661/66138304-113ed200-e607-11e9-8cbb-6b8712fbb47a.PNG)

**Comment by mtvbrianking** [comment]
Hello,

gitbash has issue displaying some ansi characters on certain versions of windows.

You can temporarily disable console by adding the `--no-ansi`

Like: `php artisan mtn-momo --no-ansi`

Alternatively, just use the default windows command instead of gitbash.

Read more: https://github.com/symfony/symfony/issues/19520
